config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#root_page'
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'

  # For session timeout
  get 'active'  => 'sessions#active'
  get 'timeout' => 'sessions#timeout'

  ### HOME PAGE ###
  resources 'dashboards', path: "dashboard", only: [:index] do
    collection do
      patch 'weekly_total/:id', to: 'dashboards#update', as: "update"
    end
  end

  ### RESOURCE NAMESPACE ##
  scope "/resources", module: 'resource', as: 'resource' do
    get 'workout-pace-chart', to: 'pace_charts#workout_pace_chart'
    get 'race-pace-chart', to: 'pace_charts#race_pace_chart'
  end

  ### ADMIN FUNCTIONS ###
  namespace :admin do
    resources :race_examples, path: "race-examples", except: [:show, :destroy]
    resources :race_distances, path: "race-distances", only: [:edit, :update]
    resources :run_types, path: "run-types", except: [:show]
    resources :shoe_brands, path: 'shoe-brands', except: [:new, :edit, :show]
    resources :user_roles, path: "user-roles", except: [:show, :destroy]
    resources :obligation_colors, path: "obligation-colors", only: [:edit, :update]

    namespace :total_record, path: 'total-records' do
      root to: 'total_records#index'
      resources :yearly_totals, path: 'yearly-totals', only: [:edit, :update]
      resources :monthly_totals, path: 'monthly-totals', only: [:edit, :update]
      resources :weekly_totals, path: 'weekly-totals', only: [:edit, :update]
    end
  end

  ### USER NAMESPACE ##
  scope "/user/:user_id", module: 'user', as: 'user' do
    resources 'calendars', only: [:index], path: "calendar" do
      collection do
        get ':id/edit', to: 'calendars#edit', as: "edit"
        patch ':id/edit', to: 'calendars#update', as: "update"
        delete ':id/destroy', to: 'calendars#destroy', as: "destroy"
        get '/new', to: 'calendars#new'
        post '/new', to: 'calendars#create'
        post '/create_current_week_runs', to: 'calendars#create_current_week_planned_runs'
        post '/copy_past_week_runs', to: 'calendars#copy_past_week_runs'
        post '/copy_current_week_runs', to: 'calendars#copy_current_week_runs'
        post '/copy_until_specific_date', to: 'calendars#copy_until_specific_date'
      end
    end

    resources :runs, except: [:show]
    resources :shoes, path: "shoes", except: [:show, :destroy]
    resources :obligations, except: [:show]

    get 'race-results', to: 'race_results#index'
    get 'statistics', to: 'statistics#index'
    post 'statistics/recalculate', to: 'statistics#recalculate_stats'

    ### USER SETTINGS PAGE ###
    get 'settings/:id/edit', to: 'settings#edit', as: 'settings_edit'
    patch 'settings/:id/edit', to: 'settings#update', as: "settings_update"
    patch 'settings/:id/edit', to: 'settings#update_password', as: "settings_update_password"
  end
end

app/controllers/user/calendars_controller.rb
class User::CalendarsController < User::UsersController
	include RunTime

	before_action :set_run, only: [:edit, :update, :destroy]
	before_action only: [:create, :update] do
		set_run_time_fields(current_user, params[:run][:hours], params[:run][:minutes], params[:run][:seconds])
	end
	before_action except: [:index, :edit] do
		website_viewer_authorization(user_calendars_path)
	end

	def index
		@obligations = current_user.obligations.includes(:state, :obligation_color)
		@runs = current_user.runs.includes(:run_type, [shoe: :shoe_brand], :state)
		@run_types = RunType.active_run_types.order_by_name
	end

	def edit
	end

	def new
		@run = Run.new
	end

	def create
		@run = Run.new(run_params)

		respond_to do |format|
			if @run.save
				format.html { redirect_to user_calendars_path, notice: create_notice(@run.name) }
				format.json { render :new, status: :created, location: @run }
			else
				format.html { render :new }
				format.json { render json: @run.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @run.update(run_params)
				format.html { redirect_to user_calendars_path, notice: update_notice(@run.name) }
				format.json { render :index, status: :ok, location: @run }
			else
				format.html { render :edit }
				format.json { render json: @run.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		respond_to do |format|
			if @run.destroy
				format.html { redirect_to user_calendars_path, notice: remove_notice(@run.name) }
				format.json { render :index, status: :ok, location: @run }
			else
				format.html { render :index }
				format.json { render json: @run.errors, status: :unprocessable_entity }
			end
		end
	end

	### CREATE PLANNED RUNS FOR CURRENT WEEK
	def create_current_week_planned_runs
		respond_to do |format|
			if current_user.create_weeklong_default_runs
				format.html { redirect_to request.referrer, notice: bold_text("Planned Runs") + " were created for the week starting " + bold_text(date_field(DateTime.current.beginning_of_week)) }
			else
				format.html { redirect_to :index }
			end
		end
	end

	### COPY LAST WEEK'S RUNS TO CURRENT WEEK
	def copy_past_week_runs
		respond_to do |format|
			if Run.copy_last_weeks_runs(current_user)
				format.html { redirect_to user_calendars_path, notice: bold_text("This Week's") + " runs were copied to the current week starting " + bold_text(date_field(DateTime.current.beginning_of_week)) }
			else
				format.html { redirect_to :index }
			end
		end
	end

	### COPY CURRENT WEEK'S RUNS TO NEXT WEEK
	def copy_current_week_runs
		respond_to do |format|
			if Run.copy_current_weeks_runs(current_user)
				format.html { redirect_to user_calendars_path, notice: bold_text("This Week's") + " runs were copied to the next week starting " + bold_text(date_field((DateTime.current+1.week).beginning_of_week)) }
			else
				format.html { redirect_to :index }
			end
		end
	end

	def copy_until_specific_date
		end_date = params[:end_date]
		if end_date.present?
			end_date = end_date.to_datetime
			respond_to do |format|
				if Run.copy_until_specific_date(current_user, end_date)
					format.html { redirect_to user_calendars_path, notice: bold_text("Current Week's") + " runs were copied to the week ending " + bold_text(date_field((end_date).end_of_week)) }
				else
					format.html { render :index }
				end
			end
		end
	end

	private
	    def set_run
			@run = current_user.runs.return_uncompleted_runs.find(params[:id])
			rescue ActiveRecord::RecordNotFound
			flash[:alert] = "You are not authorized to view specified run."
			redirect_to user_calendars_path
	    end

	    # Only allow a list of trusted parameters through.
	    def run_params
	      params.require(:run).permit(:name, :completed_run, :planned_mileage, :mileage_total, :start_time, :pace_minutes, :pace_seconds, :hours, :minutes, :seconds, :elevation_gain, :city, :notes, :personal_best, :shoe_id, :state_id, :country_id, :run_type_id)
	    end

end

app/views/user/calendars/cards/_completed-run-card.html.erb
<div class="panel panel-default card" style="border-color: <%= run.hex_code %>">
	<div class="row padding-ten">
		<div class="col-xs-12 text-center">
			<%= render "user/calendars/cards/run-heading-template", run: run %>
			<p>
				<%= mileage_and_elasped_time(run) %>
				<br />
				<%= pace_and_elevation(run) %>
			</p>
			<div><%= shoe_with_mileage(run.shoe) %></div>
		</div>
	</div>
</div>

app/views/user/calendars/cards/_obligation-card.html.erb
<div class="panel panel-default card padding-ten" style="border-color: <%=obligation.hex_code%>">
	<div class="row">
		<div class="col-xs-12 text-center">
			<div><%= bold_text(obligation.name) %></div>
			<div><small class="text-muted"><%= concat_city_state_abbreviation(obligation) %></small></div>
			<div><small class="text-muted"><%= nil_end_time_check(obligation) %></small></div>
		</div>
	</div>
</div>

app/views/user/calendars/cards/_run-heading-template.html.erb
<div><small style="color: <%=run.hex_code%>"><%= run.run_type.name %></small></div>
<%= render colored_line_divider_path, hex_code: run.hex_code %>
<div>
	<p>
		<%= bold_text(run.name) %><br />
		<small class="text-muted"><%= concat_city_state_abbreviation(run) %></small><br />
		<small class="text-muted text-center"><%= formatTime(run.start_time) %></small>
	</p>
</div>

app/views/user/calendars/cards/_uncompleted-run-card.html.erb
<div class="panel panel-default card" style="border-color: <%= run.hex_code %>">
	<div class="row padding-ten">
		<div class="col-xs-12 text-center">
			<%= render "user/calendars/cards/run-heading-template", run: run %>
			<p><%= concat_distance_miles(run.planned_mileage) %></p>
			<%= render colored_line_divider_path, hex_code: run.hex_code %>
			<%= render edit_icon_btn_path, edit_path: edit_user_calendars_path(current_user, run.id), disabled_condition: false %>
			<%= render remove_icon_btn_path, object: destroy_user_calendars_path(current_user, run.id), disabled_condition: session[:website_viewer] %>
		</div>
	</div>
</div>