config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#root_page'
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'

  # For session timeout
  get 'active'  => 'sessions#active'
  get 'timeout' => 'sessions#timeout'

  ### HOME PAGE ###
  resources 'dashboards', path: "dashboard", only: [:index] do
    collection do
      patch 'weekly_total/:id', to: 'dashboards#update', as: "update"
    end
  end

  ### RESOURCE NAMESPACE ##
  scope "/resources", module: 'resource', as: 'resource' do
    get 'workout-pace-chart', to: 'pace_charts#workout_pace_chart'
    get 'race-pace-chart', to: 'pace_charts#race_pace_chart'
  end

  ### ADMIN FUNCTIONS ###
  namespace :admin do
    resources :race_examples, path: "race-examples", except: [:show, :destroy]
    resources :race_distances, path: "race-distances", only: [:edit, :update]
    resources :run_types, path: "run-types", except: [:show]
    resources :shoe_brands, path: 'shoe-brands', except: [:new, :edit, :show]
    resources :user_roles, path: "user-roles", except: [:show, :destroy]
    resources :obligation_colors, path: "obligation-colors", only: [:edit, :update]

    namespace :total_record, path: 'total-records' do
      root to: 'total_records#index'
      resources :yearly_totals, path: 'yearly-totals', only: [:edit, :update]
      resources :monthly_totals, path: 'monthly-totals', only: [:edit, :update]
      resources :weekly_totals, path: 'weekly-totals', only: [:edit, :update]
    end
  end

  ### USER NAMESPACE ##
  scope "/user/:user_id", module: 'user', as: 'user' do
    resources 'calendars', only: [:index], path: "calendar" do
      collection do
        get ':id/edit', to: 'calendars#edit', as: "edit"
        patch ':id/edit', to: 'calendars#update', as: "update"
        delete ':id/destroy', to: 'calendars#destroy', as: "destroy"
        get '/new', to: 'calendars#new'
        post '/new', to: 'calendars#create'
        post '/create_current_week_runs', to: 'calendars#create_current_week_planned_runs'
        post '/copy_past_week_runs', to: 'calendars#copy_past_week_runs'
        post '/copy_current_week_runs', to: 'calendars#copy_current_week_runs'
        post '/copy_until_specific_date', to: 'calendars#copy_until_specific_date'
      end
    end

    resources :runs, except: [:show]
    resources :shoes, path: "shoes", except: [:show, :destroy]
    resources :obligations, except: [:show]

    get 'race-results', to: 'race_results#index'
    get 'statistics', to: 'statistics#index'
    post 'statistics/recalculate', to: 'statistics#recalculate_stats'

    ### USER SETTINGS PAGE ###
    get 'settings/:id/edit', to: 'settings#edit', as: 'settings_edit'
    patch 'settings/:id/edit', to: 'settings#update', as: "settings_update"
    patch 'settings/:id/edit', to: 'settings#update_password', as: "settings_update_password"
  end
end

app/controllers/user/calendars_controller.rb
class User::CalendarsController < User::UsersController
	include RunTime

	before_action :set_run, only: [:edit, :update, :destroy]
	before_action only: [:create, :update] do
		set_run_time_fields(current_user, params[:run][:hours], params[:run][:minutes], params[:run][:seconds])
	end
	before_action except: [:index, :edit] do
		website_viewer_authorization(user_calendars_path)
	end

	def index
		@obligations = current_user.obligations.includes(:state, :obligation_color)
		@runs = current_user.runs.includes(:run_type, [shoe: :shoe_brand], :state)
		@run_types = RunType.active_run_types.order_by_name
	end

	def edit
	end

	def new
		@run = Run.new
	end

	def create
		@run = Run.new(run_params)

		respond_to do |format|
			if @run.save
				format.html { redirect_to user_calendars_path, notice: create_notice(@run.name) }
				format.json { render :new, status: :created, location: @run }
			else
				format.html { render :new }
				format.json { render json: @run.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @run.update(run_params)
				format.html { redirect_to user_calendars_path, notice: update_notice(@run.name) }
				format.json { render :index, status: :ok, location: @run }
			else
				format.html { render :edit }
				format.json { render json: @run.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		respond_to do |format|
			if @run.destroy
				format.html { redirect_to user_calendars_path, notice: remove_notice(@run.name) }
				format.json { render :index, status: :ok, location: @run }
			else
				format.html { render :index }
				format.json { render json: @run.errors, status: :unprocessable_entity }
			end
		end
	end

	### CREATE PLANNED RUNS FOR CURRENT WEEK
	def create_current_week_planned_runs
		respond_to do |format|
			if current_user.create_weeklong_default_runs
				format.html { redirect_to request.referrer, notice: bold_text("Planned Runs") + " were created for the week starting " + bold_text(date_field(DateTime.current.beginning_of_week)) }
			else
				format.html { redirect_to :index }
			end
		end
	end

	### COPY LAST WEEK'S RUNS TO CURRENT WEEK
	def copy_past_week_runs
		respond_to do |format|
			if Run.copy_last_weeks_runs(current_user)
				format.html { redirect_to user_calendars_path, notice: bold_text("This Week's") + " runs were copied to the current week starting " + bold_text(date_field(DateTime.current.beginning_of_week)) }
			else
				format.html { redirect_to :index }
			end
		end
	end

	### COPY CURRENT WEEK'S RUNS TO NEXT WEEK
	def copy_current_week_runs
		respond_to do |format|
			if Run.copy_current_weeks_runs(current_user)
				format.html { redirect_to user_calendars_path, notice: bold_text("This Week's") + " runs were copied to the next week starting " + bold_text(date_field((DateTime.current+1.week).beginning_of_week)) }
			else
				format.html { redirect_to :index }
			end
		end
	end

	def copy_until_specific_date
		end_date = params[:end_date]
		if end_date.present?
			end_date = end_date.to_datetime
			respond_to do |format|
				if Run.copy_until_specific_date(current_user, end_date)
					format.html { redirect_to user_calendars_path, notice: bold_text("Current Week's") + " runs were copied to the week ending " + bold_text(date_field((end_date).end_of_week)) }
				else
					format.html { render :index }
				end
			end
		end
	end

	private
	    def set_run
			@run = current_user.runs.return_uncompleted_runs.find(params[:id])
			rescue ActiveRecord::RecordNotFound
			flash[:alert] = "You are not authorized to view specified run."
			redirect_to user_calendars_path
	    end

	    # Only allow a list of trusted parameters through.
	    def run_params
	      params.require(:run).permit(:name, :completed_run, :planned_mileage, :mileage_total, :start_time, :pace_minutes, :pace_seconds, :hours, :minutes, :seconds, :elevation_gain, :city, :notes, :personal_best, :shoe_id, :state_id, :country_id, :run_type_id)
	    end

end

app/controllers/user/obligations_controller.rb
class User::ObligationsController < User::UsersController
  before_action :set_obligation, only: [:edit, :update, :destroy]
  before_action :set_end_time, only: [:create, :update]

  before_action do
    website_viewer_authorization(dashboards_path)
  end

  def index
    @obligations = current_user.obligations.order_by_newest_date_time.includes(:state)
  end

  def new
    @obligation = Obligation.new
  end

  def edit
  end

  def create
    @obligation = Obligation.new(obligation_params)

    @obligation.user_id = current_user.id
    @obligation.obligation_color_id = ObligationColor.default_record.id

    respond_to do |format|
      if @obligation.save
        format.html { redirect_to user_obligations_path, notice: create_notice(@obligation.name) }
        format.json { render :index, status: :created, location: @obligation }
      else
        format.html { render :new }
        format.json { render json: @obligation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @obligation.update(obligation_params)
        format.html { redirect_to user_obligations_path, notice: update_notice(@obligation.name) }
        format.json { render :index, status: :ok, location: @obligation }
      else
        format.html { render :edit }
        format.json { render json: @obligation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @obligation.destroy
    respond_to do |format|
      format.html { redirect_to user_obligations_path, notice: remove_notice(@obligation.name) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_obligation
      @obligation = current_user.obligations.find(params[:id])
    end

    def set_end_time
      @obligation.end_time = nil if not params[:check_end_time].nil?
    end

    # Only allow a list of trusted parameters through.
    def obligation_params
      params.require(:obligation).permit(:name, :start_time, :end_time, :check_end_time, :city, :state_id, :country_id)
    end
end

app/controllers/user/race_results_controller.rb
class User::RaceResultsController < User::UsersController
	before_action :set_current_user_races, :set_geo_chart_hash

	def index
		### ALL RACE RESULTS OF CURRENT USER ###
		@race_results = @races.order_by_most_recent.group_by_year

		### PERSONAL BESTS SECTION ###
		### COUNTS OF RACE DISTANCES ###
		@race_distance_counts = @races.return_race_distance_counts
		### COLUMN WIDTH DEPENDING ON NUMBER DIFFERENT OF RACES DISTANCE ###
		race_count = @race_distance_counts.size
		@rd_counts_column_spacing = 12/(race_count == 0 ? 1 : race_count)
		### DATA TO POPULATE MAP OF U.S.A. ###
		@us_geo_chart_data = @us_geo_chart_hash.map{ |key, value| [State.find(key).name, value] }
		@world_geo_chart_data = @world_geo_chart_hash.map{ |key, value| [Country.find(key).name, value] }
		### PERSONAL BESTS ARRAY ###
		@personal_bests = current_user.personal_best_races
	end

	private
	def set_current_user_races
		@races = current_user.runs.return_races.includes(:state, shoe: :shoe_brand)
	end

	def set_geo_chart_hash
		@us_geo_chart_hash = @races.where.not(:state_id => nil).group(:state_id).count
		@world_geo_chart_hash = @races.includes(:country).group(:country_id).count
	end
end

app/controllers/user/runs_controller.rb
class User::RunsController < User::UsersController
  include RunTime

  before_action :set_run, only: [:edit, :update, :destroy]
  before_action only: [:create, :update] do
    set_run_time_fields(current_user, params[:run][:hours], params[:run][:minutes], params[:run][:seconds])
  end
  before_action only: [:create, :update, :destroy] do
    website_viewer_authorization(user_runs_path)
  end

  def index
    @runs = current_user.return_completed_runs.includes(:run_type, shoe: :shoe_brand).order_by_most_recent
  end

  def new
    @run = Run.new
  end

  def edit
  end

  def create
    @run = Run.new(run_params)

    respond_to do |format|
      if @run.save
        format.html { redirect_to user_runs_path, notice: create_notice(@run.name) }
        format.json { render :new, status: :created, location: @run }
      else
        format.html { render :new }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to user_runs_path, notice: update_notice(@run.name) }
        format.json { render :index, status: :ok, location: @run }
      else
        format.html { render :edit }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @run.destroy
        format.html { redirect_to user_runs_path, notice: remove_notice(@run.name) }
        format.json { render :index, status: :ok, location: @run }
      else
        format.html { render :index }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = current_user.runs.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "You are not authorized to view specified run."
      redirect_to user_runs_path
    end

    # Only allow a list of trusted parameters through.
    def run_params
      params.require(:run).permit(:name, :completed_run, :planned_mileage, :mileage_total, :start_time, :pace_minutes, :pace_seconds, :hours, :minutes, :seconds, :elevation_gain, :city, :notes, :personal_best, :shoe_id, :state_id, :country_id, :run_type_id)
    end

end

app/controllers/user/settings_controller.rb
class User::SettingsController < User::UsersController
  before_action :set_user, only: [:edit, :update, :update_password]
  before_action only: [:update, :update_password] do
    website_viewer_authorization(user_settings_edit_path(current_user))
  end

  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found

  def edit
    @website_viewer = User.return_website_viewer
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to user_settings_edit_path(current_user), notice: update_notice("Your Profile") }
        format.json { render :edit, status: :ok, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_password
    respond_to do |format|
      if current_user.update_with_password(user_password_params)
        format.html { redirect_to user_settings_edit_path(current_user), notice: update_notice("Your Password") }
      else
        format.html { render :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
      ### IF USER DOESN'T MATCH CURRENT USER OR IS ARCHIVED
      if current_user != @user || current_user.is_archived?
        flash[:alert] = "Access Denied."
        redirect_to user_settings_edit_path(current_user)
      end
    end

    def handle_record_not_found
      # Send it to the view that is specific for User not found
      flash[:alert] = "Record not Found."
      redirect_to dashboards_path
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :default_city, :default_state, :time_zone, :password_digest)
    end
end

app/controllers/user/shoes_controller.rb
class User::ShoesController < User::UsersController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]
  before_action only: [:create, :update] do
    website_viewer_authorization(user_shoes_path)
  end

  def index
    @all_user_shoes = current_user.shoes.includes(:shoe_brand)
    @active_shoes = @all_user_shoes.active_shoes
    @retired_shoes = @all_user_shoes.retired_shoes
  end

  def new
    @shoe = Shoe.new
  end

  def edit
  end

  def create
    @shoe = Shoe.new(shoe_params)

    set_shoe_fields
    @shoe.save

    respond_to do |format|
      if check_for_retired_shoe
        format.html { redirect_to user_shoes_path, notice: create_notice(@shoe.return_full_shoe_name) }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    set_shoe_fields
    @shoe.update(shoe_params)

    respond_to do |format|
      if check_for_retired_shoe
        format.html { redirect_to user_shoes_path, notice: update_notice(@shoe.return_full_shoe_name) }
        format.json { render :index, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = current_user.shoes.find(params[:id])
    end

    def set_shoe_fields
      @shoe.user_id = current_user.id
      @shoe.remove_other_default_shoes if shoe_params[:default]=="1"
    end

    def check_for_retired_shoe
      shoe_params[:retired]=="1" ? @shoe.retire_shoe : @shoe.unretire_shoe
    end

    # Only allow a list of trusted parameters through.
    def shoe_params
      params.require(:shoe).permit(:model, :color_way, :image, :forefoot_stack, :heel_stack, :heel_drop, :weight, :size, :shoe_type, :previous_mileage, :new_mileage, :default, :purchased_on, :first_used_on, :retired, :retired_on, :shoe_brand_id)
    end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  include ControllerNotice
  include UserAuthorization

  before_action :check_user_id

  private
  def check_user_id
    if current_user.id != params[:user_id].to_i
      flash[:alert] = "Access Denied."
      redirect_to dashboards_path
    end
  end

end

app/views/user/calendars/_copy-runs-until-date-modal.html.erb
<div class="modal fade" id="copySpecificDateModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title text-center" id="aboutAddModal">Copy This Week's Runs Until Specified Date</h1>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12">
						<p class="text-center">Date MUST BE 2+ weeks from current date.</p>
					</div>
				</div>
				<br />
				<div class="row vertical-align-middle">
					<div class="col-xs-4 text-right">
						<%= form_with(url: copy_until_specific_date_user_calendars_path, method: "post") do %>
							<%= label_tag(:end_date, "Copy Until:") %>
					</div>
					<div class="col-xs-8">
						<%= date_field_tag(:end_date, DateTime.current, class: 'form-control') %>
					</div>
				</div>
			</div>
			<div class="modal-footer">
					<%= submit_tag 'Cancel', :type => 'button', class: "btn btn-danger", data: { toggle: 'modal', 'target': "#copySpecificDateModal" } %>
					<%= submit_tag("Submit", class: 'btn btn-success') %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/user/calendars/_run-type-listing.html.erb
<span style="color: <%=run_type.hex_code%>"><%= run_type.name %></span>

app/views/user/calendars/copy_until_specific_date.js.erb
$(function() {
	location.reload();
	$('#copySpecificDateModal').modal('hide');
}); 

app/views/user/calendars/edit.html.erb
<%= render edit_header_path, path: user_calendars_path, btn_text: "Calendar" %>

<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-default">
			<div class="panel-heading text-center">
				<h1>Editing: <%= bold_text(@run.name) %></h1>
			</div>
			<div class="panel-body">
				<%= render "user/runs/form", run: @run, action: "update", shoe_selection: Shoe.of_user(current_user).select_edit_shoe_id_name, disable_form: @run.determine_run_modification_by_user_role %>
			</div
		</div>
	</div>
</div>

app/views/user/calendars/index.html.erb
<div class="row">
	<div class="col-md-2 col-xs-12 col-md-offset-1">
		<%= link_to "Add a Run on Specific Date", new_user_calendars_path, { class: "btn btn-info btn-block", :disabled => session[:website_viewer] } %>
	</div>
	<div class="col-md-2 col-xs-12">
		<%= button_to "Create this Week's Planned Runs", create_current_week_runs_user_calendars_path, { class: "btn btn-primary btn-block", :disabled => session[:website_viewer] } %>
	</div>
	<div class="col-md-2 col-xs-12">
		<%= button_to "Copy Last Week's Runs to This Week", copy_past_week_runs_user_calendars_path, { class: "btn btn-danger btn-block", :disabled => session[:website_viewer] } %>
	</div>
	<div class="col-md-2 col-xs-12">
		<%= button_to "Copy This Week's Runs to Next Week", copy_current_week_runs_user_calendars_path, { class: "btn btn-success btn-block", :disabled => session[:website_viewer] } %>
	</div>
	<div class="col-md-2 col-xs-12">
		<%= button_tag "Copy This Week's Runs Until Specific Date", :class => "btn btn-warning btn-block", :disabled => session[:website_viewer], data: { toggle: 'modal', target: '#copySpecificDateModal' } %>
		<%= render "copy-runs-until-date-modal" %>
	</div>
</div>
<hr />

<div class="row">
	<div class="col-md-12">
		<p class="text-center">
			<% @run_types.take(@run_types.count-1).each do |run_type| %>
				<%= render "user/calendars/run-type-listing", run_type: run_type %> |
			<% end %>
			<%= render "user/calendars/run-type-listing", run_type: @run_types.last %>
		</p>
	</div>
</div>

<%= render notice_path %>
<%= render alert_path %>

<div class="row">
	<div class="col-md-12">
		<%= month_calendar(partial: '/user/calendars/simple_calendar/month_calendar', attribute: :start_time, events: @runs+@obligations) do |date, events| %>
			<h5><%= bold_text(date) %></h5>

			<% events.each do |event| %>
				<% if event.is_event? %>
					<%= render "user/calendars/cards/obligation-card", obligation: event %>
				<% else %>
					<% partial_name = event.was_completed? ? "completed-run-card" : "uncompleted-run-card" %>
					<%= render "user/calendars/cards/" + partial_name, run: event %>
				<% end %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/user/calendars/new.html.erb
<%= render new_header_path, path: calendars_path, btn_text: "Calendar" %>

<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-default">
			<div class="panel-heading text-center">
				<h1>Add New Run</h1>
			</div>
			<div class="panel-body">
				<%= render "runs/form", run: @run, action: "new", disable_form: session[:website_viewer] %>
			</div>
		</div>
	</div>
</div>