config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#root_page'
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'

  # For session timeout
  get 'active'  => 'sessions#active'
  get 'timeout' => 'sessions#timeout'

  ### HOME PAGE ###
  resources 'dashboards', path: "dashboard", only: [:index] do
    collection do
      patch 'weekly_total/:id', to: 'dashboards#update', as: "update"
    end
  end

  ### RESOURCE NAMESPACE ##
  scope "/resources", module: 'resource', as: 'resource' do
    get 'workout-pace-chart', to: 'pace_charts#workout_pace_chart'
    get 'race-pace-chart', to: 'pace_charts#race_pace_chart'
  end

  ### ADMIN FUNCTIONS ###
  namespace :admin do
    resources :race_examples, path: "race-examples", except: [:show, :destroy]
    resources :race_distances, path: "race-distances", only: [:edit, :update]
    resources :run_types, path: "run-types", except: [:show]
    resources :shoe_brands, path: 'shoe-brands', except: [:new, :edit, :show]
    resources :user_roles, path: "user-roles", except: [:show, :destroy]
    resources :obligation_colors, path: "obligation-colors", only: [:edit, :update]

    namespace :total_record, path: 'total-records' do
      root to: 'total_records#index'
      resources :yearly_totals, path: 'yearly-totals', only: [:edit, :update]
      resources :monthly_totals, path: 'monthly-totals', only: [:edit, :update]
      resources :weekly_totals, path: 'weekly-totals', only: [:edit, :update]
    end
  end

  ### USER NAMESPACE ##
  scope "/user/:user_id", module: 'user', as: 'user' do
    resources 'calendars', only: [:index], path: "calendar" do
      collection do
        get ':id/edit', to: 'calendars#edit', as: "edit"
        patch ':id/edit', to: 'calendars#update', as: "update"
        delete ':id/destroy', to: 'calendars#destroy', as: "destroy"
        get '/new', to: 'calendars#new'
        post '/new', to: 'calendars#create'
        post '/create_current_week_runs', to: 'calendars#create_current_week_planned_runs'
        post '/copy_past_week_runs', to: 'calendars#copy_past_week_runs'
        post '/copy_current_week_runs', to: 'calendars#copy_current_week_runs'
        post '/copy_until_specific_date', to: 'calendars#copy_until_specific_date'
      end
    end

    resources :runs, except: [:show]
    resources :shoes, path: "shoes", except: [:show, :destroy]
    resources :obligations, except: [:show]

    get 'race-results', to: 'race_results#index'
    get 'statistics', to: 'statistics#index'
    post 'statistics/recalculate', to: 'statistics#recalculate_stats'

    ### USER SETTINGS PAGE ###
    get 'settings/:id/edit', to: 'settings#edit', as: 'settings_edit'
    patch 'settings/:id/edit', to: 'settings#update', as: "settings_update"
    patch 'settings/:id/edit', to: 'settings#update_password', as: "settings_update_password"
  end
end

app/models/modules/total_record.rb
module Modules::TotalRecord
	def of_user(user)
		where(:user => user)
	end

	def unfrozen_records
		where(:frozen_flag => false)
	end

	def frozen_records
		where(:frozen_flag => true)
	end

  	### USED UPON LOGIN TO FREEZE YEARLY TOTALS THAT ARE NOT CURRENT YEARLY ###
	def freeze_total_records_collection
		self.update_all(frozen_flag: true)
	end

end

app/controllers/admin/total_record/monthly_totals_controller.rb
class Admin::TotalRecord::MonthlyTotalsController < Admin::TotalRecord::TotalRecordsController
  before_action :set_monthly_total, only: [:edit, :update]

  def edit
  end

  def update
    respond_to do |format|
      if @monthly_total.update(monthly_total_params)
        format.html { redirect_to admin_total_record_root_path, notice: update_notice(@monthly_total.month_start.strftime("%B %Y")) }
      else
        format.html { render :edit }
        format.json { render json: @monthly_total.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monthly_total
      @monthly_total = current_user.monthly_totals.unfrozen_records.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "You are not authorized to edit specified Monthly Total."
      redirect_to admin_total_record_root_path
    end

    # Only allow a list of trusted parameters through.
    def monthly_total_params
      params.require(:monthly_total).permit(:previous_mileage, :new_mileage, :previous_number_of_runs, :new_number_of_runs, :previous_elevation_gain, :new_elevation_gain, :previous_time_in_seconds, :new_time_in_seconds, :frozen_flag)
    end

end

app/controllers/admin/total_record/total_records_controller.rb
class Admin::TotalRecord::TotalRecordsController < Admin::AdminController
  def index
    @yearly_totals = current_user.yearly_totals.order_by_recent_year.includes(:monthly_totals)
    @weekly_totals = current_user.weekly_totals.order_by_recent_week
  end
end

app/controllers/admin/total_record/weekly_totals_controller.rb
class Admin::TotalRecord::WeeklyTotalsController < Admin::TotalRecord::TotalRecordsController
  before_action :set_weekly_total, only: [:edit, :update]

  def edit
  end

  def update
    respond_to do |format|
      if @weekly_total.update(weekly_total_params)
        format.html { redirect_to admin_total_record_root_path, notice: "Weekly Total Record starting " + bold_text(date_field((@weekly_total.week_start))) + " was successfully updated." }
      else
        format.html { render :edit }
        format.json { render json: @weekly_total.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weekly_total
      @weekly_total = current_user.weekly_totals.unfrozen_records.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "You are not authorized to edit specified Weekly Total."
      redirect_to admin_total_record_root_path
    end

    # Only allow a list of trusted parameters through.
    def weekly_total_params
      params.require(:weekly_total).permit(:mileage_total, :mileage_goal, :met_goal, :number_of_runs, :time_in_seconds, :elevation_gain, :frozen_flag)
    end
end

app/controllers/admin/total_record/yearly_totals_controller.rb
class Admin::TotalRecord::YearlyTotalsController < Admin::TotalRecord::TotalRecordsController
  before_action :set_yearly_total, only: [:edit, :update]

  def edit
  end

  def update
    respond_to do |format|
      if @yearly_total.update(yearly_total_params)
        format.html { redirect_to admin_total_record_root_path, notice: update_notice(@yearly_total.year) }
      else
        format.html { render :edit }
        format.json { render json: @yearly_total.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yearly_total
      @yearly_total = current_user.yearly_totals.unfrozen_records.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "You are not authorized to edit specified Yearly Total."
      redirect_to admin_total_record_root_path
    end

    # Only allow a list of trusted parameters through.
    def yearly_total_params
      params.require(:yearly_total).permit(:mileage_total, :number_of_runs, :elevation_gain, :time_in_seconds, :frozen_flag)
    end
end

app/views/admin/total_record/total_records/_yearly-monthly-form.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h1>Editing: <%= bold_text(heading) %></h1>
      </div>
      <div class="panel-body">
        <%= form_with(model: [:admin, :total_record, total_record], local: true, class: "form-horizontal", html: { autocomplete: "off" }) do |f| %>
          <%= render "templates/alerts/form-errors", model: total_record %>

          <div class="row text-center">
            <div class="col-xs-2 col-xs-offset-1">
              <%= f.label :number_of_runs, 'Number of Runs:' %>
              <%= f.number_field :number_of_runs, { class: 'form-control', step: 1, placeholder: "0 runs", :disabled => disable_form } %>
            </div>
            <div class="col-xs-3">
              <%= f.label :mileage_total, 'Mileage Total:' %>
              <%= f.number_field :mileage_total, { class: 'form-control', step: 0.01, placeholder: "0 miles", :disabled => disable_form } %>
            </div>
            <div class="col-xs-2">
              <%= f.label :elevation_gain, 'Elevation:' %>
              <%= f.number_field :elevation_gain, { class: 'form-control', step: 1, placeholder: "0 ft.", :disabled => disable_form } %>
            </div>
            <div class="col-xs-2">
              <%= f.label :time_in_seconds, 'Time in Seconds:' %>
              <%= f.number_field :time_in_seconds, { class: 'form-control', step: 1, placeholder: "0 seconds", :disabled => disable_form } %>
            </div>
            <div class="col-xs-1">
              <%= f.label :frozen_flag, 'Freeze Record?', { class: "pointer-cursor make-text-unselectable", :disabled => disable_form } %>
                <%= f.check_box :frozen_flag, {} %>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-md-4 col-md-offset-4">
              <%= f.submit "Save Changes", class: "btn btn-success btn-block", :disabled => disable_form %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/total_record/total_records/index.html.erb
<%= render index_header_path, heading_text: "Total Records" %>
<%= render alert_path %>
<br />

<div class="row">
	<div class="col-sm-3">
		<div class="list-group text-center">
			<% @yearly_totals.each do |yearly_total| %>
				<a class="list-group-item" id="<%=yearly_total.year%>-navbar" href="#<%=yearly_total.year%>-panel" data-toggle="tab">
					<h4 class="list-group-item-heading"><%= yearly_total.year %></h4>
				</a>
			<% end %>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="tab-content">
			<% @yearly_totals.each do |yearly_total| %>
				<div id="<%=yearly_total.year%>-panel" class="panel panel-default tab-pane fade in">
					<div class="panel-heading text-center">
						<h1 class="panel-title"><%= yearly_total.year %></h1>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-xs-6 col-xs-offset-3 text-center">
								<p><%= concat_run_totals_line_one(yearly_total) %></p>
								<p><%= concat_run_totals_line_two(yearly_total) %></p>
							</div>
							<div class="col-xs-3 text-right">
								<%= render edit_btn_path, edit_path: edit_admin_total_record_yearly_total_path(yearly_total), disabled_condition: yearly_total.is_frozen? %>
							</div>
						</div>
						<br />
						<div class="row">
							<div class="col-xs-12">
								<table class="table table-responsive table-striped table-hover table-responsive">
									<thead>
										<tr>
											<th colspan="2"></th>
										</tr>
									</thead>
									<tbody>
										<% yearly_total.monthly_totals.each do |monthly_total| %>
											<tr class="text-center">
												<td><%= format_month(monthly_total.month_start) %></td>
												<td><%= one_lined_totals(monthly_total) %></td>
												<td><%= render edit_icon_btn_path, edit_path: edit_admin_total_record_monthly_total_path(monthly_total), disabled_condition: monthly_total.is_frozen? %></td>
											</tr>
										<% end %>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col-sm-3">
		<div class="list-group">
			<% @weekly_totals.each do |weekly_total| %>
				<div class="panel panel-default text-center">
					<div class="panel-heading">
						<div class="row text-center">
							<h4 class="list-group-item-heading"><%= formatshortenedDateRange(weekly_total.week_start, weekly_total.week_end) %></h4>
						</div>
					</div>
					<div class="panel-body">
						<div class="row text-center">
							<div class="col-sm-12">
								<%= render weekly_mileage_progress_path, object: weekly_total %>
							</div>
						</div>
						<div class="row text-center">
							<div class="col-sm-9">
								<p class="list-group-item-text"><%= wt_records_one_lined_total(weekly_total) %></p>
							</div>
							<div class="col-sm-3">
								<%= render edit_icon_btn_path, edit_path: edit_admin_total_record_weekly_total_path(weekly_total), disabled_condition: weekly_total.is_frozen? %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>